#!/bin/sh -e

#
# 1. File to upload.
#
upload() {
    file=$1; shift
    curl -sF "fichier=@$file" http://www.noelshack.com/api.php
}

#
# 1. Gallery URL to convert to raw URL.
#
parse() {
    url=$1; shift
    search='www\.noelshack\.com\/([0-9]+)-([0-9]+)-(.+)'
    replace='image\.noelshack\.com\/fichiers\/\1\/\2\/\3'
    echo "$url" | sed -r "s/$search/$replace/g"
}

#
# 1. File to upload.
#
main() {
    file=$1; shift

    if echo "$file" | grep -qE '^\w+://'; then
        url=$file
        mkdir -p /tmp/noelup
        file=/tmp/noelup/$(basename "$url")
        curl -so "$file" "$url"
    fi

    if [ ! -f "$file" ]; then
        echo 'Invalid file.' >&2
        exit 1
    fi

    url=$(upload "$file")
    parse "$url"
}

main "$@"
